# Assignment

Import numpy as np

In [1]:
import numpy as np


Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
l = [1,2,3,4,5]
np_array = np.array(l)
np_array

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [5]:
mat = np.arange(1,10)
mat=mat.reshape(3,3)
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [6]:
mat_1 = np.arange(1,18,2)
mat_1 = mat_1.reshape(3,3)
mat_1


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [9]:
l = []
for i in range(10):
    l.append(np.random.rand()*10)
l = np.array(l)
print(l)
                # or
l_1 = np.random.rand(10)*10
print(l_1)

[9.60622639 7.93315879 1.06005131 3.02433195 4.75561026 3.74443726
 0.49241742 1.57597375 6.2083995  1.14429637]
[8.66875657 6.48754809 6.92880228 6.18335801 0.55963943 1.20980126
 3.77596708 2.21831921 8.93099806 1.06098543]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [10]:
array = np.array([1,2,3,4,5])
array = array.reshape(5,1)
array

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [12]:
array.shape


(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [19]:
l = np.random.rand(10)
l[[2,3,8]]

[0.01108294 0.22794189 0.13940376 0.51245357 0.74419438 0.84962155
 0.06874947 0.83008698 0.07153265 0.61527676]
[0.13940376 0.51245357 0.07153265]


Print alternate elements of that array

In [20]:
l[::2]


array([0.01108294, 0.13940376, 0.74419438, 0.06874947, 0.07153265])

Change last 3 elements into 100 using broadcasting and print

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.